# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ ](blue)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[username]
style_user = "cyan bold"
style_root = "black bold"
format = "($style) "
disabled = false
show_always = true

[lua]
disabled = true

[python]
symbol = " "
pyenv_version_name = true

