/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_anybar.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "focusdir.h"
#include "focusurgent.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "insets.h"
#include "killunsel.h"
#include "moveresize.h"
#include "reorganizetags.h"
#include "restartsig.h"
#include "roundedcorners.h"
#include "scratchpad.h"
#include "scratchpad_alt_1.h"
#include "seamless_restart.h"
#include "sticky.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

