/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_anybar.c"
#include "bar_ewmhtags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "distributetags.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "focusfollowmouse.c"
#include "insets.c"
#include "movestack.c"
#include "push.c"
#include "restartsig.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "scratchpad_alt_1.c"
#include "shift.c"
#include "shiftviewclients.c"
#include "togglefullscreen.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "warp.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_horizgrid.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

