/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_anybar.h"
#include "bar_ewmhtags.h"
#include "bar_wintitle.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "distributetags.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "focusfollowmouse.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "insets.h"
#include "keymodes.h"
#include "movestack.h"
#include "push.h"
#include "roundedcorners.h"
#include "scratchpad_alt_1.h"
#include "shift.h"
#include "shiftview.h"
#include "togglefullscreen.h"
#include "transfer.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

