/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_statuscolors.c"
#include "bar_winicon.c"
#include "bar_tagpreview.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "cfacts.c"
#include "distributetags.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "movestack.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "roundedcorners.c"
#include "scratchpad_alt_1.c"
#include "shift.c"
#include "shiftview.c"
#include "tagall.c"
#include "tagallmon.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

