/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_statuscolors.h"
#include "bar_winicon.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "aspectresize.h"
#include "attachx.h"
#include "cfacts.h"
#include "distributetags.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "movestack.h"
#include "reorganizetags.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "roundedcorners.h"
#include "scratchpad_alt_1.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftview.h"
#include "tagall.h"
#include "tagallmon.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_columns.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"

